#!/usr/bin/env python

from mininet.topo import Topo

class topo_test(Topo):

    def __init__(self):

        Topo.__init__(self)

        h1  = self.addHost('h1')
        h2  = self.addHost('h2')
    	h3  = self.addHost('h3')
	    h4  = self.addHost('h4')
	    h5  = self.addHost('h5')
        h6  = self.addHost('h6')
        h7  = self.addHost('h7')
	    h8  = self.addHost('h8')
	    h9  = self.addHost('h9')
	    h10 = self.addHost('h10')
        h11 = self.addHost('h11')
        h12 = self.addHost('h12')
	    h13 = self.addHost('h13')
	    h14 = self.addHost('h14')
	    h15 = self.addHost('h15')
        h16 = self.addHost('h16')
        h17 = self.addHost('h17')
	    h18 = self.addHost('h18')
	    h19 = self.addHost('h19')
	    h20 = self.addHost('h20')
        h21 = self.addHost('h21')
        h22 = self.addHost('h22')
	    h23 = self.addHost('h23')
	    h24 = self.addHost('h24')
	    h25 = self.addHost('h25')
        h26 = self.addHost('h26')
        h27 = self.addHost('h27')
	    h28 = self.addHost('h28')
	    h29 = self.addHost('h29')
	    h30 = self.addHost('h30')
        h31 = self.addHost('h31')
        h32 = self.addHost('h32')
	    h33 = self.addHost('h33')
	    h34 = self.addHost('h34')
	    h35 = self.addHost('h35')
	    h36 = self.addHost('h36')
	    h37 = self.addHost('h37')
	    h38 = self.addHost('h38')
	    h39 = self.addHost('h39')
	    h40 = self.addHost('h40')
	    h41 = self.addHost('h41')
	    h42 = self.addHost('h42')
	    h43 = self.addHost('h43')
	    h44 = self.addHost('h44')
	    h45 = self.addHost('h45')
	    h46 = self.addHost('h46')
	    h47 = self.addHost('h47')
	    h48 = self.addHost('h48')
	    h49 = self.addHost('h49')
	    h50 = self.addHost('h50')
	    h51 = self.addHost('h51')
	    h52 = self.addHost('h52')
	    h53 = self.addHost('h53')
	    h54 = self.addHost('h54')
	    h55 = self.addHost('h55')
	    h56 = self.addHost('h56')
	    h57 = self.addHost('h57')
	    h58 = self.addHost('h58')
	    h59 = self.addHost('h59')
	    h60 = self.addHost('h60')
	    h61 = self.addHost('h61')
	    h62 = self.addHost('h62')
	    h63 = self.addHost('h63')
	    h64 = self.addHost('h64')
	    h65 = self.addHost('h65')
	    h66 = self.addHost('h66')
	    h67 = self.addHost('h67')
	    h68 = self.addHost('h68')
	    h69 = self.addHost('h69')
	    h70 = self.addHost('h70')
        self.addLink(h1, s1)
        self.addLink(h2, s1)
        self.addLink(h3, s1)
        self.addLink(h4, s1)
        self.addLink(h5, s1)
        self.addLink(h6, s1)
        self.addLink(h7, s1)
        self.addLink(s1, s2)
        self.addLink(s1, s3)
        self.addLink(s1, s4)
        self.addLink(h8, s2)
        self.addLink(h9, s2)
        self.addLink(h10, s2)
        self.addLink(h11, s2)
        self.addLink(h12, s2)
        self.addLink(h13, s2)
        self.addLink(h14, s2)
        self.addLink(s2, s5)
        self.addLink(s2, s3)
        self.addLink(h15, s3)
        self.addLink(h16, s3)
        self.addLink(h17, s3)
        self.addLink(h18, s3)
        self.addLink(h19, s3)
        self.addLink(h20, s3)
        self.addLink(h21, s3)
        self.addLink(s3, s4)
        self.addLink(s3, s5)
        self.addLink(h22, s4)
        self.addLink(h23, s4)
        self.addLink(h24, s4)
        self.addLink(h25, s4)
	    self.addLink(h26, s4)
        self.addLink(h27, s4)
        self.addLink(h28, s4)
        self.addLink(s4, s5)
        self.addLink(h29, s5)
        self.addLink(h30, s5)
        self.addLink(h31, s5)
        self.addLink(h32, s5)
        self.addLink(h33, s5)
        self.addLink(h34, s5)
        self.addLink(h35, s5)
        self.addLink(s5, s6)
        self.addLink(s5, s7)
        self.addLink(h36, s6)
        self.addLink(h37, s6)
        self.addLink(h38, s6)
        self.addLink(h39, s6)
        self.addLink(h40, s6)
        self.addLink(h41, s6)
        self.addLink(h42, s6)
        self.addLink(s6, s7)
        self.addLink(s6, s8)
        self.addLink(s6, s9)
        self.addLink(h43, s7)
        self.addLink(h44, s7)
        self.addLink(h45, s7)
        self.addLink(h46, s7)
        self.addLink(h47, s7)
        self.addLink(h48, s7)
        self.addLink(h49, s7)
        self.addLink(s7, s8)
        self.addLink(s7, s10)
        self.addLink(h50, s8)
        self.addLink(h51, s8)
        self.addLink(h52, s8)
        self.addLink(h53, s8)
        self.addLink(h54, s8)
        self.addLink(h55, s8)
        self.addLink(h56, s8)
        self.addLink(s8, s9)
        self.addLink(s8, s10)
        self.addLink(h57, s9)
        self.addLink(h58, s9)
        self.addLink(h59, s9)
        self.addLink(h60, s9)
        self.addLink(h61, s9)
        self.addLink(h62, s9)
        self.addLink(h63, s9)
        self.addLink(h64, s10)
        self.addLink(h65, s10)
        self.addLink(h66, s10)
        self.addLink(h67, s10)
        self.addLink(h68, s10)
        self.addLink(h69, s10)
        self.addLink(h70, s10)