#!/usr/bin/env python

from mininet.topo import Topo

class topo_test(Topo):

    def __init__(self):

        Topo.__init__(self)

        h1  = self.addHost('h1')
        h2  = self.addHost('h2')
        h3  = self.addHost('h3')
        h4  = self.addHost('h4')
        h5  = self.addHost('h5')
        h6  = self.addHost('h6')
        h7  = self.addHost('h7')
        h8  = self.addHost('h8')
        h9  = self.addHost('h9')
        h10 = self.addHost('h10')
        h11 = self.addHost('h11')
        h12 = self.addHost('h12')
        h13 = self.addHost('h13')
        h14 = self.addHost('h14')
        h15 = self.addHost('h15')
        h16 = self.addHost('h16')
        h17 = self.addHost('h17')
        h18 = self.addHost('h18')
        h19 = self.addHost('h19')
        h20 = self.addHost('h20')
        h21 = self.addHost('h21')
        h22 = self.addHost('h22')
        h23 = self.addHost('h23')
        h24 = self.addHost('h24')
        h25 = self.addHost('h25')
        h26 = self.addHost('h26')
        h27 = self.addHost('h27')
        h28 = self.addHost('h28')
        h29 = self.addHost('h29')
        h30 = self.addHost('h30')
        h31 = self.addHost('h31')
        h32 = self.addHost('h32')
        h33 = self.addHost('h33')
        h34 = self.addHost('h34')
        h35 = self.addHost('h35')
        
        s1 = self.addSwitch('s1')
        s2 = self.addSwitch('s2')
        s3 = self.addSwitch('s3')
        s4 = self.addSwitch('s4')
        s5 = self.addSwitch('s5')

        self.addLink(h1, s1)
        self.addLink(h2, s1)
        self.addLink(h3, s1)
        self.addLink(h4, s1)
        self.addLink(h5, s1)
        self.addLink(h6, s1)
        self.addLink(h7, s1)
        self.addLink(s1, s2)
        self.addLink(s1, s3)
        self.addLink(s1, s4)
        self.addLink(h8, s2)
        self.addLink(h9, s2)
        self.addLink(h10, s2)
        self.addLink(h11, s2)
        self.addLink(h12, s2)
        self.addLink(h13, s2)
        self.addLink(h14, s2)
        self.addLink(s2, s5)
        self.addLink(s2, s3)
        self.addLink(h15, s3)
        self.addLink(h16, s3)
        self.addLink(h17, s3)
        self.addLink(h18, s3)
        self.addLink(h19, s3)
        self.addLink(h20, s3)
        self.addLink(h21, s3)
        self.addLink(s3, s4)
        self.addLink(s3, s5)
        self.addLink(h22, s4)
        self.addLink(h23, s4)
        self.addLink(h24, s4)
        self.addLink(h25, s4)
        self.addLink(h26, s4)
        self.addLink(h27, s4)
        self.addLink(h28, s4)
        self.addLink(s4, s5)
        self.addLink(h29, s5)
        self.addLink(h30, s5)
        self.addLink(h31, s5)
        self.addLink(h32, s5)
        self.addLink(h33, s5)
        self.addLink(h34, s5)
        self.addLink(h35, s5)
